version: '3.2'
services:

  app1:
    build:
      context: app1
      dockerfile: Dockerfile
    image: app1
    ports:
      - "1001:80"
    container_name: app1
   

  app2:
    build:
      context: app2
      dockerfile: Dockerfile
    image: app2
    ports:
      - "1002:80"
    container_name: app2

  loadbalancer:
      build: load-balancer
      links:
          - app1
          - app2
      ports:
          - '3000:8080'